### ISSUE TITLE
Add excludeOverriden to QueryOptions

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/smoke#21]
Currently I'm running into an issue with the Polymer.dart 0.17 port, https://github.com/dart-lang/polymer-dart/issues/531, where smoke will return multiple instances of a field when said field is declared in a superclass.

I would like to add an option that excludes duplicated fields/methods from the query results.

**Comment by eernstg** [comment]
Considering the connection to reflectable, I'll inject a comment here:

Adding an `excludeOverridden` feature to smoke queries may be a perfectly valid choice, but there is a reason why overridden declarations are not excluded in `dart:mirrors` and (due to the compatible-unless-we-really-want-otherwise policy we have) in `reflectable`. The point is that there are two alternative points of view on the target substance that reflection may deal with: Runtime entities, and source code. From the runtime entity point of view, an object has no fields, but it may have getters and setters, including some getters and setters which have been created implicitly, based on a field declaration; from the runtime entity point of view there is no inheritance hierarchy, there is only an instance that has a certain behavior (consequently, overridden members are not available). From the source code point of view fields do exist, and each class along an inheritance chain up to `Object` is treated separately . Hence, with `declarations` (which uses the source code point of view) you get fields, no hierarchy, no hiding-of-overridden, etc.; and with `instanceMembers` you get no fields, only methods (including getters and setters, possibly generated).

The concept of `excludeOverridden` inherently mixes the two points of view, which makes me think that maybe you don't want it.  ;-)
